<?php

namespace CodeCats\PanelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneRepository extends EntityRepository
{
    public function findAllByUserId($id)
    {

    }
}
