<?php

namespace CodeCats\PanelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProgressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgressRepository extends EntityRepository
{
}
