<?php

namespace CodeCats\PanelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProgressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgressRepository extends EntityRepository
{
    public function findFront($start = 0, $limit = 25)
    {
        $qb = $this->createQueryBuilder('p');

        //$queryCounter = $qb;

        $qb->setFirstResult($start);
        $qb->setMaxResults($limit);

        return array(
            'data'  => $qb->getQuery()->getResult(),
            'total' => $qb->select('COUNT(p)')->getQuery()->getSingleScalarResult()
        );
    }
}
