<?php

namespace CodeCats\PanelBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
    SELECT *, sum(datediff(p.ended, p.started)) as progress_days FROM User u
    left join Progress p
    on  p.user_id = u.id
    group by u.id
    order by progress_days DESC
     *
     * @param int $max
     * @return array
     */
    public function findMostActive($max = 10)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u', 'p')->addSelect('SUM(DATEDIFF(p.ended, p.started)) as progress_days')
            ->leftJoin('u.progresses', 'p')->groupBy('u.id')->orderBy('progress_days', 'desc')->setMaxResults($max);

        return $qb->getQuery()->getResult();
    }
}
