parameters:
#    code_cats_front.example.class: CodeCats\FrontBundle\Example

services:
#    code_cats_front.example:
#        class: %code_cats_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
