parameters:
#    code_cats_core.example.class: CodeCats\CoreBundle\Example

services:
  code_cats_core.frontend_autoloader:
    class: CodeCats\CoreBundle\Service\FrontendAutoloader
    arguments: [@kernel, @fire_php]
#    code_cats_core.example:
#        class: %code_cats_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
