parameters:
#    code_cats_core.example.class: CodeCats\CoreBundle\Example

services:
#    code_cats_core.example:
#        class: %code_cats_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
