messages:
    pl: "Polski"
    en: "English"
    fr: "Français"
    es: "Español"
    it: "Italiano"
    de: "Deutsh"
    lt: "Lietuvių"
    zh: "汉语"
    ru: "язык"
    ja: "日本"
    ko: "한국어"
    ar: "اللغة العربية"