code_cats_test_homepage:
  pattern:  /hello/{name}
  defaults: { _controller: CodeCatsTestBundle:Default:index }

code_cats_test_render:
  pattern: /
  defaults: { _controller: CodeCatsTestBundle:Default:render }